# VARIABLES
$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend

general {
    lock_cmd = $lock_cmd # command run when hyprlock is requested
    before_sleep_cmd = $lock_cmd # lock before the system goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on # ensure display wakes up after sleep
}

# SCREEN BRIGHTNESS (Power Saving)
listener {
    timeout = 150 # 2.5mins
    on-timeout = brightnessctl -s set 10 # save current brightness and dim to 10%
    on-resume = brightnessctl -r # restore previous brightness
}

# LOCKSCREEN
listener {
    timeout = 180 # 3mins
    on-timeout = $lock_cmd   
}

# DPMS (Monitor Power Management)
listener {
    timeout = 210 # 3:30mins
    on-timeout = hyprctl dispatch dpms off # turn off display
    on-resume = hyprctl dispatch dpms on # turn on display
}

# SYSTEM SUSPEND
listener {
    timeout = 540 # 9mins
    on-timeout = $suspend_cmd                   
}